### ISSUE TITLE
move documentation to the wiki

### ISSUE THREAD

**Issue by gld1982ltd** [skeleton-framework/skeleton-framework#17]
Documentation started... drop in at the wiki to help out.

**Comment by enlore** [comment]
Got a big chunk in. Please feel free to fix spelling and grammatical errors, offer clarification, etc.  I'll be reviewing and revising in the coming week as well.

**Comment by gld1982ltd** [comment]
Cool. No prob. I'll be contributing mostly to the 2.0-dev branch in the next week or so. I'll definitely help make sure the final 1.x.x version will be stable and all repos organized with all documentation intact before we release 2.0
