### ISSUE TITLE
Skeleton nav on example page disappears with width <750 px

### ISSUE THREAD

**Issue by alexjj** [skeleton-framework/skeleton-framework#28]
Technically the nav bar on [the demo page](https://skeletonframework.github.io/) isn't part of the core skeleton css, but it generally fits well. However, it disappears for screens with width less than 750px. At which point there's no navigation altogether.

**Comment by gld1982ltd** [comment]
That particular navbar will more than likely be replaced with the next update to the Skeleton Framework website.
