### ISSUE TITLE
Capitulate to Apple?

### ISSUE THREAD

**Issue by Maxhirez** [skeleton-framework/skeleton-framework#32]
What's the community's opinion on adding mqs for the new iOS 9 half screens on iPads?
eg:
```
/*ipad landscape split-screen safari*/
		@media only screen 
			and (width:507px) 
			and (height:660px){
			.some-class{some-rule:stupidpx;}
		}
/*ipad landscape split-screen Chrome*/
		@media only screen 
			and (width:507px) 
			and (height:653px){
			.some-class{some-rule:stupidpx;}
		}

```
These overlap the abandoned skeleton queries but they at least let you target some elements.

**Comment by enlore** [comment]
I'd say it's out of scope.  Skeleton's goal is to be a starting point for projects, and this sort of decision making is too particular to individual project needs.

**Comment by Maxhirez** [comment]
Right then.  Sounds ggod.
