### ISSUE TITLE
SCSS or LESS?

### ISSUE THREAD

**Issue by Mortiferr** [skeleton-framework/skeleton-framework#36]
Enhancement request:
use`scss` or `less` as your css pre-processor. I feel it would help efficiency as this project grows.

**Comment by enlore** [comment]
We talked about using various pre-processors, but settled on pure css (with some post-css) to keep things simple. There are forks of the original Skeleton that are written using different pre-processors, though.

Further, the core CSS (probably) won't need much growing for the time being. The heart and soul of the project is to serve as a starting point for your own work, intended such that you take it and make it your own to suit your needs.

Thanks for the suggestion.

**Comment by Mortiferr** [comment]
I understand! I really like that idea. /close
