### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by GianniCasagrande** [skeleton-framework/skeleton-framework#37]
Hi there,
Used this for many of my personal sites, but building an enterprise app now.

Is there support for IE? Mainly IE8 - IE7?
I'd assume .js would be used for IE7 media queries? Have you guys gone down this path?

Just looking for some info before I dig more. Thanks!

**Comment by enlore** [comment]
There is not support for older IE. Skeleton is focused on mobile and modern, keeping it small and rather forward leaning.  It would probably make a great foundation for a project that needs to support older IE, but those features aren't in scope for the core CSS.

I think you're right about needing a Javascript polyfill for doing media queries in old IE, though I'm not the best person to advise you on that. I've had the good fortune of never needing to support old IE.

**Comment by GianniCasagrande** [comment]
Thanks so much!
