### ISSUE TITLE
.u-full-width should have max-width: none;

### ISSUE THREAD

**Issue by r3wt** [skeleton-framework/skeleton-framework#39]
otherwise it can't override max width of `.container`

thoughts?

**Comment by gld1982ltd** [comment]
I think that for something to be outside the container it should be placed outside the container in the code. I have been away for a little while, but give me a few days to sort through all of your advice.

Pull requests are welcome.

**Comment by enlore** [comment]
Basically yeah. The point of the `.u-full-width` class is to style an element in context, not to bust it out of its containing context. Useful for inline-block elements like buttons.
