### ISSUE TITLE
Git merge artifacts in release 1.0.9 CSS files

### ISSUE THREAD

**Issue by thevulch** [skeleton-framework/skeleton-framework#43]
I'm not sure if CSS still works, but there's merge artifacts in the release `.zip`, top of the file:

> ~\> head `skeleton.css`:

```css
<<<<<<< HEAD
/*! Skeleton Framework | 1.0.9 | MIT | Apr 11th, 2016 */
=======
/*! Skeleton Framework | 1.0.8 | MIT | Apr 11th, 2016 */
>>>>>>> enlore#master

/* Table of contents
- Grid
- Base Styles
- Typography
```

`skeleton.min.css` is even worse.

**Comment by gld1982ltd** [comment]
Ouch. Fix in progress.

**Comment by gld1982ltd** [comment]
Yeah, I uploaded the wrong zip. This won't happen once we get automated releases set up.
