### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by asifkabani** [skeleton-framework/skeleton-framework#57]
I noticed the new skeleton.css file has offsets and different size classes (xs, sm, md, lg). Is there any documentation describing how to use these?

**Comment by enlore** [comment]
There is no documentation about those on the Wiki, but the `dist/index.html` file shows an example of their use. If you aren't sure how to use them based on the example, I'll be happy to answer more questions about them.

**Comment by asifkabani** [comment]
Thanks! I'll dig around in there.

**Comment by enlore** [comment]
For sure. Let em know if you have any questions.
