### ISSUE TITLE
Usability - margin under headers could be smaller

### ISSUE THREAD

**Issue by Pudlovich** [skeleton-framework/skeleton-framework#59]
I'm currently working in a project which uses Skeleton, and one of the issues I had to address is that the margin under a header is almost as big as the one over it.
Most guidelines I've seen recommend that it should be smaller, so that the text "belongs to" the heading, as it increases comprehension and enables faster skimming.

The question is - what do you think of such change? Is a PR welcome?

**Comment by acrox999** [comment]
I agree with this completely. One of the first things I do when I use
Skeleton is to fix the margins. Some of them are ridiculous, like the ones
below the headings.

**Comment by enlore** [comment]
It's funny you both say this, as I also consistently redo the margins when I start using Skeleton for a project. PR certainly welcome!
